// constants/cars.ts

export const cars = [
  {
    id: 1,
    name: "Koenigsegg",
    type: "Sport",
    price: "$99.00",
    fuel: "90L",
    transmission: "Manual",
    capacity: "2 People",
    image: "/images/car1.svg",
  },
  {
    id: 2,
    name: "Nissan GT - R",
    type: "Sport",
    price: "$80.00",
    fuel: "80L",
    transmission: "Manual",
    capacity: "2 People",
    image: "/images/car2.svg",
  },
  {
    id: 3,
    name: "Rolls-Royce",
    type: "Sadan",
    price: "$96.00/",
    fuel: "95L",
    transmission: "Manual",
    capacity: "4 People",
    image: "/images/car3.svg",
  },
  {
    id: 4,
    name: "Nissan GT - R",
    type: "Sport",
    price: "$80.00",
    fuel: "80L",
    transmission: "Manual",
    capacity: "2 People",
    image: "/images/car4.svg",
  },
];



export const cars2 = [
  {
    id: 1,
    name: "AllNew Rush",
    type: "Suv",
    price: "$72.00",
    fuel: "70L",
    transmission: "Manual",
    capacity: "6 People",
    image: "/images/car01.png",
  },
  {
    id: 2,
    name: "CR -V",
    type: "Suv",
    price: "$80.00",
    fuel: "80L",
    transmission: "Manual",
    capacity: "6 People",
    image: "/images/car02.png",
  },
  {
    id: 3,
    name: "AllNew Terios",
    type: "Suv",
    price: "$74.00",
    fuel: "90L",
    transmission: "Manual",
    capacity: "6 People",
    image: "/images/car03.png",
  },
  {
    id: 4,
    name: "CR -V",
    type: "Suv",
    price: "$80.00",
    fuel: "80L",
    transmission: "Manual",
    capacity: "6 People",
    image: "/images/car04.png",
  },
];

export const cars3 = [
  {
    id: 1,
    name: "MGZX Exclusice",
    type: "Hatchback",
    price: "$76.00",
    fuel: "70L",
    transmission: "Manual",
    capacity: "4 People",
    image: "/images/car001.png",
  },
  {
    id: 2,
    name: "NewMGZS",
    type: "Suv",
    price: "$80.00",
    fuel: "80L",
    transmission: "Manual",
    capacity: "6 People",
    image: "/images/car002.png",
  },
  {
    id: 3,
    name: "MGZX Exclusice",
    type: "Hatchback",
    price: "$76.00",
    fuel: "70L",
    transmission: "Manual",
    capacity: "4 People",
    image: "/images/car001.png",
  },
  {
    id: 4,
    name: "NewMGZS",
    type: "Suv",
    price: "$80.00",
    fuel: "80L",
    transmission: "Manual",
    capacity: "6 People",
    image: "/images/car004.png",
  },
];

